#### Pruebas para la API de Perfiles
#### Prueba de creación de un perfil
POST http://localhost:3000/api/estados
Content-Type: application/json

{
  "nombre": "Por hacer",
  "descripcion": "Tarea aún no iniciada"
}

#### Prueba de mostrar perfiles
GET http://localhost:3000/api/estados

#### Prueba de mostrar un perfil específico
GET http://localhost:3000/api/perfiles/2

#### Prueba de actualización de un perfil
PUT http://localhost:3000/api/prioridades/1
Content-Type: application/json

{
  "nombre": "Media",
  "descripcion": "Tiene prioridad media"
}

#### Prueba de eliminación de un perfil
DELETE http://localhost:3000/api/etiquetas/2