#### Pruebas para la API de Perfiles
#### Prueba de creación de un perfil
POST http://localhost:3000/api/come
Content-Type: application/json

{
  "texto": "Buen trabajo",
  "id_tarea": 1,
  "id_usuario": 3
}

#### Prueba de mostrar perfiles
GET http://localhost:3000/api/actividades

#### Prueba de mostrar un perfil específico
GET http://localhost:3000/api/perfiles/2

#### Prueba de actualización de un perfil
PUT http://localhost:3000/api/perfiles/6
Content-Type: application/json

{
  "nombre": "Administrador5"
}

#### Prueba de eliminación de un perfil
DELETE http://localhost:3000/api/etiquetas/2